version: "3"

services:
  blockxdnode0:
    container_name: blockxdnode0
    image: "blockxd/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-blockxd.log}
    volumes:
      - ./localnet-setup/node0/blockxd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  blockxdnode1:
    container_name: blockxdnode1
    image: "blockxd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-blockxd.log}
    volumes:
      - ./localnet-setup/node1/blockxd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  blockxdnode2:
    container_name: blockxdnode2
    image: "blockxd/node"
    environment:
      - ID=2
      - LOG=${LOG:-blockxd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/blockxd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  blockxdnode3:
    container_name: blockxdnode3
    image: "blockxd/node"
    environment:
      - ID=3
      - LOG=${LOG:-blockxd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/blockxd:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
